import type { Company } from "./types";

// 数値（売上高・営業利益率）はいずれも直近期のIR資料などをもとにした
// "規模感をつかむための目安"。為替・年度・会計基準の違いで前後するため、
// 厳密な最新値は各社のIR情報を参照してください。
export const COMPANIES: Company[] = [
  // ── ファウンドリ（受託製造） ─────────────────────────────
  {
    id: "tsmc",
    name: "TSMC",
    nameJa: "台湾積体電路製造",
    country: "台湾",
    flag: "🇹🇼",
    region: "global",
    segments: ["foundry"],
    revenueUsdB: 90,
    operatingMarginPct: 42,
    founded: 1987,
    hq: "新竹",
    tagline: "世界のロジック半導体の心臓部を一手に引き受ける、受託製造の絶対王者。",
    businessModel:
      "Apple・NVIDIA・AMDなど「設計だけ」を行うファブレス企業から製造を一括受託し、最先端プロセスの量産で稼ぐ。自社ブランド製品は持たない。",
    strengths: ["最先端プロセス量産で圧倒的シェア", "Apple/NVIDIA等トップ顧客を独占", "設備投資の規模で他社を突き放す"],
    rivals: ["samsung", "globalfoundries", "umc", "intel"],
    colors: ["#f97316", "#c2410c"],
  },
  {
    id: "globalfoundries",
    name: "GlobalFoundries",
    nameJa: "グローバルファウンドリーズ",
    country: "米国",
    flag: "🇺🇸",
    region: "global",
    segments: ["foundry"],
    revenueUsdB: 6.8,
    operatingMarginPct: 20,
    founded: 2009,
    hq: "ニューヨーク州モールタ",
    tagline: "最先端は追わない、と割り切った成熟プロセスの実力者。",
    businessModel:
      "微細化競争の最前線からは距離を置き、車載・通信向けなど成熟プロセスの受託製造に特化して安定収益を狙う。AMDの自社工場が独立して誕生。",
    strengths: ["成熟プロセスに特化し高稼働率を維持", "米国内生産で政府支援を追い風に", "車載・通信向けの安定顧客基盤"],
    rivals: ["tsmc", "samsung", "umc"],
    colors: ["#fb923c", "#c2410c"],
  },
  {
    id: "umc",
    name: "UMC",
    nameJa: "聯華電子",
    country: "台湾",
    flag: "🇹🇼",
    region: "global",
    segments: ["foundry"],
    revenueUsdB: 7.5,
    operatingMarginPct: 20,
    founded: 1980,
    hq: "新竹",
    tagline: "TSMCと同じ台湾発、成熟ノードの堅実な二番手。",
    businessModel:
      "先端プロセスではTSMCに及ばないが、汎用ロジック向けの受託製造で高い稼働率を維持し安定的に稼ぐ。",
    strengths: ["成熟ノードでの高い生産効率", "幅広い顧客ポートフォリオ", "台湾のエコシステムを活用"],
    rivals: ["tsmc", "globalfoundries"],
    colors: ["#fdba74", "#ea580c"],
  },

  // ── IDM／メモリ ───────────────────────────────────────
  {
    id: "samsung",
    name: "Samsung Electronics",
    nameJa: "サムスン電子",
    country: "韓国",
    flag: "🇰🇷",
    region: "global",
    segments: ["idm", "memory", "foundry"],
    revenueUsdB: 66,
    operatingMarginPct: 15,
    founded: 1969,
    hq: "水原",
    tagline: "メモリからロジックまで垂直統合、半導体のオールラウンダー。",
    businessModel:
      "DRAM/NAND型メモリの世界最大手であると同時に、他社設計品を製造するファウンドリ事業も持つ数少ない総合半導体企業。半導体以外にスマホ・家電も抱える。",
    strengths: ["メモリで世界最大の生産規模", "設計〜製造〜完成品まで垂直統合", "潤沢な投資体力"],
    rivals: ["tsmc", "sk-hynix", "micron", "intel"],
    colors: ["#7c3aed", "#4c1d95"],
  },
  {
    id: "intel",
    name: "Intel",
    nameJa: "インテル",
    country: "米国",
    flag: "🇺🇸",
    region: "global",
    segments: ["idm", "foundry"],
    revenueUsdB: 53,
    operatingMarginPct: 2,
    founded: 1968,
    hq: "サンタクララ",
    tagline: "PC・サーバーCPUの巨人。自社工場を武器に反撃を狙う。",
    businessModel:
      "自社設計のCPUを自社工場で製造して販売するIDMモデルが祖業。近年は他社製品の受託製造（Intel Foundry）にも参入し反転攻勢中だが収益は苦戦。",
    strengths: ["PC/サーバーCPUの圧倒的な設置ベース", "自社ファブという希少資産", "x86アーキテクチャの互換性資産"],
    rivals: ["amd", "tsmc", "samsung", "nvidia"],
    colors: ["#8b5cf6", "#4c1d95"],
  },
  {
    id: "ti",
    name: "Texas Instruments",
    nameJa: "テキサス・インスツルメンツ",
    country: "米国",
    flag: "🇺🇸",
    region: "global",
    segments: ["idm"],
    revenueUsdB: 15.6,
    operatingMarginPct: 35,
    founded: 1930,
    hq: "ダラス",
    tagline: "地味だけど手堅い、アナログ半導体の隠れた巨人。",
    businessModel:
      "電源管理ICやセンサーなど、目立たないが多品種のアナログ半導体を自社工場で大量生産。息の長い製品を薄く広く売り続けて稼ぐ。",
    strengths: ["10万品目超という圧倒的な製品ラインアップ", "自社300mmファブによる原価優位", "分散した顧客基盤で景気耐性が高い"],
    rivals: ["stmicro", "infineon"],
    colors: ["#9333ea", "#581c87"],
  },
  {
    id: "stmicro",
    name: "STMicroelectronics",
    nameJa: "STマイクロエレクトロニクス",
    country: "スイス／仏伊",
    flag: "🇪🇺",
    region: "global",
    segments: ["idm"],
    revenueUsdB: 13.3,
    operatingMarginPct: 15,
    founded: 1987,
    hq: "ジュネーブ",
    tagline: "自動車・産業機器を陰で支える欧州の総合半導体メーカー。",
    businessModel:
      "車載・産業機器向けマイコンやパワー半導体を自社工場で一貫生産する欧州最大級のIDM。フランス・イタリア政府がバックにいる合弁出自。",
    strengths: ["車載マイコンで世界トップシェア級", "SiCパワー半導体への早期投資", "欧州域内での垂直統合生産"],
    rivals: ["infineon", "nxp", "ti"],
    colors: ["#a855f7", "#6b21a8"],
  },
  {
    id: "infineon",
    name: "Infineon Technologies",
    nameJa: "インフィニオン テクノロジーズ",
    country: "ドイツ",
    flag: "🇩🇪",
    region: "global",
    segments: ["idm"],
    revenueUsdB: 15,
    operatingMarginPct: 20,
    founded: 1999,
    hq: "ノイビベルク",
    tagline: "電気を制御する力＝パワー半導体の世界王者。",
    businessModel:
      "電力変換用パワー半導体や車載マイコンに強みを持つ欧州IDM。EV・再生可能エネルギーの普及を追い風に成長を続ける。シーメンスの半導体部門が独立して誕生。",
    strengths: ["パワー半導体で世界首位級シェア", "EV/再エネ需要を正面から取り込む", "車載セキュリティチップにも強み"],
    rivals: ["stmicro", "nxp", "ti"],
    colors: ["#c084fc", "#7e22ce"],
  },
  {
    id: "nxp",
    name: "NXP Semiconductors",
    nameJa: "NXPセミコンダクターズ",
    country: "オランダ",
    flag: "🇳🇱",
    region: "global",
    segments: ["idm", "fabless"],
    revenueUsdB: 12.6,
    operatingMarginPct: 25,
    founded: 2006,
    hq: "アイントホーフェン",
    tagline: "車載ネットワークとセキュリティに強い縁の下の力持ち。",
    businessModel:
      "自動車・IoT向けマイコンや通信チップを手掛け、自動運転化で1台あたりの半導体搭載数が増えるほど恩恵を受ける。フィリップスの半導体部門が源流。",
    strengths: ["車載通信・セキュリティチップに強み", "自動車の電子化トレンドが追い風", "多様な顧客との長期関係"],
    rivals: ["infineon", "stmicro", "ti"],
    colors: ["#d8b4fe", "#7e22ce"],
  },
  {
    id: "sk-hynix",
    name: "SK hynix",
    nameJa: "SKハイニックス",
    country: "韓国",
    flag: "🇰🇷",
    region: "global",
    segments: ["memory"],
    revenueUsdB: 53,
    operatingMarginPct: 25,
    founded: 1983,
    hq: "利川",
    tagline: "HBM（広帯域メモリ）でAI半導体の脇役から主役級へ。",
    businessModel:
      "DRAM・NAND型メモリの製造販売が中心。AI向け高性能メモリHBMでNVIDIAの主要サプライヤーとなり収益が急拡大した。",
    strengths: ["HBM（AI向け高帯域メモリ）で先行者優位", "DRAMで世界トップクラスのシェア", "SKグループの投資体力"],
    rivals: ["samsung", "micron"],
    colors: ["#f59e0b", "#92400e"],
  },
  {
    id: "micron",
    name: "Micron Technology",
    nameJa: "マイクロン・テクノロジー",
    country: "米国",
    flag: "🇺🇸",
    region: "global",
    segments: ["memory"],
    revenueUsdB: 25,
    operatingMarginPct: 15,
    founded: 1978,
    hq: "ボイシ",
    tagline: "メモリ価格サイクルの荒波を生き抜く米国唯一の総合メモリ大手。",
    businessModel:
      "DRAM・NANDメモリの設計・製造・販売を行う。市況（メモリの需給サイクル）で収益が大きく上下する、装置産業型のコモディティビジネス。",
    strengths: ["米国籍で唯一の総合メモリメーカー", "先端DRAMプロセスでの技術力", "自国生産で政策支援も追い風"],
    rivals: ["samsung", "sk-hynix", "kioxia"],
    colors: ["#fbbf24", "#b45309"],
  },

  // ── ファブレス ────────────────────────────────────────
  {
    id: "nvidia",
    name: "NVIDIA",
    nameJa: "エヌビディア",
    country: "米国",
    flag: "🇺🇸",
    region: "global",
    segments: ["fabless"],
    revenueUsdB: 130,
    operatingMarginPct: 55,
    founded: 1993,
    hq: "サンタクララ",
    tagline: "GPU一本足からAI計算基盤の帝王へ。",
    businessModel:
      "GPU（画像処理用半導体）の設計に特化するファブレス企業。製造はTSMCに委託し、AIの学習・推論向けデータセンター向けGPUで爆発的成長を遂げた。",
    strengths: ["AI向けGPUで圧倒的シェア", "CUDAというソフトウェア資産で囲い込み", "データセンター需要の急拡大を独占的に享受"],
    rivals: ["amd", "broadcom", "intel"],
    colors: ["#22c55e", "#166534"],
  },
  {
    id: "amd",
    name: "AMD",
    nameJa: "アドバンスト・マイクロ・デバイセズ",
    country: "米国",
    flag: "🇺🇸",
    region: "global",
    segments: ["fabless"],
    revenueUsdB: 26,
    operatingMarginPct: 10,
    founded: 1969,
    hq: "サンタクララ",
    tagline: "万年チャレンジャーから、CPUもGPUも戦える実力者へ。",
    businessModel:
      "CPU・GPUを設計しTSMCに製造委託するファブレス企業。もとは自社工場を持つIDMだったが工場を切り離し身軽になった。PC/サーバーCPUでIntelと、GPUでNVIDIAと同時に戦う稀有な立ち位置。",
    strengths: ["CPU・GPU両方を手掛ける唯一に近い存在", "TSMC最先端プロセスへのアクセス", "データセンターCPUでシェア拡大中"],
    rivals: ["intel", "nvidia"],
    colors: ["#16a34a", "#14532d"],
  },
  {
    id: "qualcomm",
    name: "Qualcomm",
    nameJa: "クアルコム",
    country: "米国",
    flag: "🇺🇸",
    region: "global",
    segments: ["fabless"],
    revenueUsdB: 39,
    operatingMarginPct: 28,
    founded: 1985,
    hq: "サンディエゴ",
    tagline: "スマホの頭脳と特許ロイヤリティで二重に稼ぐ。",
    businessModel:
      "スマートフォン向けSoC「Snapdragon」の設計販売に加え、通信規格（3G/4G/5G）の必須特許ライセンス収入も大きな柱を成す。",
    strengths: ["スマホ向けSoCで高いシェア", "通信特許による安定ロイヤリティ収入", "車載・PC領域への多角化"],
    rivals: ["broadcom"],
    colors: ["#4ade80", "#15803d"],
  },
  {
    id: "broadcom",
    name: "Broadcom",
    nameJa: "ブロードコム",
    country: "米国",
    flag: "🇺🇸",
    region: "global",
    segments: ["fabless"],
    revenueUsdB: 51,
    operatingMarginPct: 40,
    founded: 1991,
    hq: "サンノゼ",
    tagline: "通信チップと大型M&Aソフトウェアの二刀流。",
    businessModel:
      "データセンター・通信向けのカスタムチップ(ASIC)や無線チップを設計・供給する半導体事業と、M&Aで取り込んだエンタープライズソフト事業を併せ持つ。",
    strengths: ["AI向けカスタムASICで大手クラウド企業と直結", "Wi-Fi/Bluetoothチップで高シェア", "大型買収によるソフトウェア収益の積み上げ"],
    rivals: ["qualcomm", "nvidia"],
    colors: ["#65a30d", "#365314"],
  },

  // ── 製造装置 ──────────────────────────────────────────
  {
    id: "asml",
    name: "ASML",
    nameJa: "エーエスエムエル",
    country: "オランダ",
    flag: "🇳🇱",
    region: "global",
    segments: ["equipment"],
    revenueUsdB: 28,
    operatingMarginPct: 33,
    founded: 1984,
    hq: "フェルトホーフェン",
    tagline: "最先端チップの生殺与奪を握る、露光装置のラスボス。",
    businessModel:
      "先端ロジック半導体の製造に不可欠なEUV露光装置を世界で唯一供給する。1台数百億円という超高額装置をTSMC・Samsung・Intelに販売し圧倒的な独占収益を得る。",
    strengths: ["EUV露光装置を実質的に独占", "参入障壁が極めて高い精密光学技術", "顧客の投資計画を左右する交渉力"],
    rivals: ["tel", "applied-materials"],
    colors: ["#0d9488", "#134e4a"],
  },
  {
    id: "applied-materials",
    name: "Applied Materials",
    nameJa: "アプライド マテリアルズ",
    country: "米国",
    flag: "🇺🇸",
    region: "global",
    segments: ["equipment"],
    revenueUsdB: 27,
    operatingMarginPct: 29,
    founded: 1967,
    hq: "サンタクララ",
    tagline: "成膜・エッチングなど幅広い工程をカバーする装置業界の総合商社的存在。",
    businessModel:
      "半導体製造の様々な工程（成膜・エッチング等）向け装置を幅広くラインアップし、世界中のFabに販売・保守サービスで稼ぐ。",
    strengths: ["製造装置のラインアップの広さ", "世界最大級の装置売上規模", "保守・部材による継続収益"],
    rivals: ["lam-research", "tel", "kla"],
    colors: ["#14b8a6", "#115e59"],
  },
  {
    id: "lam-research",
    name: "Lam Research",
    nameJa: "ラムリサーチ",
    country: "米国",
    flag: "🇺🇸",
    region: "global",
    segments: ["equipment"],
    revenueUsdB: 14.9,
    operatingMarginPct: 28,
    founded: 1980,
    hq: "フリーモント",
    tagline: "微細な溝を掘る「エッチング」のスペシャリスト。",
    businessModel:
      "エッチング（回路の溝を削る工程）や成膜装置に強みを持つ専業メーカー。メモリ向け装置の比率が高く、メモリ市況の波を受けやすい。",
    strengths: ["エッチング装置で高いシェア", "メモリメーカーとの太いパイプ", "微細化に伴う工程数増加が追い風"],
    rivals: ["applied-materials", "tel"],
    colors: ["#2dd4bf", "#0f766e"],
  },
  {
    id: "kla",
    name: "KLA Corporation",
    nameJa: "ケーエルエー",
    country: "米国",
    flag: "🇺🇸",
    region: "global",
    segments: ["equipment"],
    revenueUsdB: 11.9,
    operatingMarginPct: 38,
    founded: 1975,
    hq: "ミルピタス",
    tagline: "不良品を見逃さない検査装置の絶対王者。",
    businessModel:
      "半導体の欠陥を検出する検査・計測装置でトップシェアを握る。プロセスが微細化するほど検査ニーズが増える構造的な強みを持つ。",
    strengths: ["検査・計測装置で世界トップシェア", "微細化トレンドが追い風になる構造", "高い営業利益率"],
    rivals: ["applied-materials", "advantest"],
    colors: ["#5eead4", "#0f766e"],
  },

  // ── EDA / IP ─────────────────────────────────────────
  {
    id: "arm",
    name: "Arm Holdings",
    nameJa: "アーム・ホールディングス",
    country: "英国",
    flag: "🇬🇧",
    region: "global",
    segments: ["ip"],
    revenueUsdB: 3.2,
    operatingMarginPct: 20,
    founded: 1990,
    hq: "ケンブリッジ",
    tagline: "スマホの大半に眠る、縁の下のライセンス王。",
    businessModel:
      "CPUの設計図（命令セットアーキテクチャ／コア）を各社にライセンス供与し、チップ1個ごとのロイヤリティで稼ぐ、製造を持たない究極のファブレス。孫正義率いるソフトバンクグループが親会社。",
    strengths: ["スマホ向けCPUコアで圧倒的な採用実績", "低消費電力設計に強み", "ロイヤリティ収入で数量に連動して稼ぐ"],
    rivals: ["synopsys", "cadence"],
    colors: ["#ec4899", "#831843"],
  },
  {
    id: "synopsys",
    name: "Synopsys",
    nameJa: "シノプシス",
    country: "米国",
    flag: "🇺🇸",
    region: "global",
    segments: ["eda", "ip"],
    revenueUsdB: 6.1,
    operatingMarginPct: 20,
    founded: 1986,
    hq: "サニーベール",
    tagline: "全てのチップ設計者が使う、見えないインフラ。",
    businessModel:
      "半導体の回路設計に使うEDAソフトウェアやIPをライセンス販売するサブスクリプション型ビジネス。チップを作る会社は必ずといっていいほど利用する。",
    strengths: ["EDA市場でCadenceと並ぶ最大手", "設計フロー全体をカバーするツール群", "高い顧客ロックイン"],
    rivals: ["cadence", "arm"],
    colors: ["#f472b6", "#9d174d"],
  },
  {
    id: "cadence",
    name: "Cadence Design Systems",
    nameJa: "ケイデンス・デザイン・システムズ",
    country: "米国",
    flag: "🇺🇸",
    region: "global",
    segments: ["eda"],
    revenueUsdB: 4.6,
    operatingMarginPct: 27,
    founded: 1988,
    hq: "サンノゼ",
    tagline: "Synopsysと二強を成す設計ツールのもう一方の雄。",
    businessModel:
      "チップの設計・検証に使うソフトウェアをライセンス提供。EDA市場をSynopsysと二分する寡占ビジネスで高い利益率を誇る。",
    strengths: ["EDA市場でSynopsysと並ぶ二強", "検証ツールでの高い評価", "サブスクリプション型の安定収益"],
    rivals: ["synopsys"],
    colors: ["#fb7185", "#9f1239"],
  },

  // ── 日本企業 ──────────────────────────────────────────
  {
    id: "tel",
    name: "東京エレクトロン",
    nameJa: "Tokyo Electron",
    country: "日本",
    flag: "🇯🇵",
    region: "japan",
    segments: ["equipment"],
    revenueUsdB: 14,
    operatingMarginPct: 24,
    founded: 1963,
    hq: "東京",
    tagline: "日本が誇る半導体装置のメガプレイヤー。",
    businessModel:
      "成膜・エッチング・コーターデベロッパーなど幅広い製造装置を手掛け、世界の主要ファブに導入される日本発のグローバル装置メーカー。",
    strengths: ["コーター/デベロッパーで世界トップシェア", "幅広い工程をカバーする製品群", "TSMC・Samsung等主要顧客への浸透"],
    rivals: ["applied-materials", "lam-research", "asml"],
    colors: ["#0ea5e9", "#075985"],
  },
  {
    id: "renesas",
    name: "ルネサス エレクトロニクス",
    nameJa: "Renesas Electronics",
    country: "日本",
    flag: "🇯🇵",
    region: "japan",
    segments: ["idm", "fabless"],
    revenueUsdB: 10,
    operatingMarginPct: 30,
    founded: 2010,
    hq: "東京",
    tagline: "日本の車載マイコンを支える統合再編の申し子。",
    businessModel:
      "車載・産業機器向けマイコン(MCU)を中心に、自社生産と外部委託を組み合わせるファブライト戦略で幅広い顧客に供給する。日立・三菱電機・NECの半導体部門統合から誕生。",
    strengths: ["車載マイコンで世界トップクラスのシェア", "自社工場と外部委託を使い分けるファブライト", "積極的なM&Aでの事業拡張"],
    rivals: ["nxp", "infineon", "stmicro"],
    colors: ["#38bdf8", "#0369a1"],
  },
  {
    id: "kioxia",
    name: "キオクシア",
    nameJa: "Kioxia",
    country: "日本",
    flag: "🇯🇵",
    region: "japan",
    segments: ["memory"],
    revenueUsdB: 9,
    operatingMarginPct: 15,
    founded: 2017,
    hq: "東京",
    tagline: "NAND型フラッシュメモリを世界で初めて発明した「生みの親」。",
    businessModel:
      "旧東芝が発明したNANDフラッシュメモリの製造販売が事業の柱。米Western Digitalと四日市・北上工場を共同運営する合弁生産モデルが特徴。",
    strengths: ["NAND発明企業としての技術基盤", "Western Digitalとの共同生産体制", "四日市・北上の大規模生産拠点"],
    rivals: ["samsung", "sk-hynix", "micron"],
    colors: ["#eab308", "#854d0e"],
  },
  {
    id: "advantest",
    name: "アドバンテスト",
    nameJa: "Advantest",
    country: "日本",
    flag: "🇯🇵",
    region: "japan",
    segments: ["equipment"],
    revenueUsdB: 3.3,
    operatingMarginPct: 25,
    founded: 1954,
    hq: "東京",
    tagline: "できあがったチップの合否を判定する検査装置の世界大手。",
    businessModel:
      "半導体の最終検査に使うテスター(検査装置)を製造販売。AI半導体の高性能化・高付加価値化で検査ニーズが増え業績が拡大している。",
    strengths: ["半導体テスターで世界トップシェア級", "AI半導体向け検査需要の拡大を享受", "米Teradyneと二強体制"],
    rivals: ["kla"],
    colors: ["#06b6d4", "#164e63"],
  },
  {
    id: "screen",
    name: "SCREENホールディングス",
    nameJa: "SCREEN Holdings",
    country: "日本",
    flag: "🇯🇵",
    region: "japan",
    segments: ["equipment"],
    revenueUsdB: 2.9,
    operatingMarginPct: 15,
    founded: 1943,
    hq: "京都",
    tagline: "ウェハーを洗う「洗浄装置」で世界トップシェア。",
    businessModel:
      "半導体ウェハーの洗浄装置で世界首位級のシェアを持つ京都発の装置メーカー。印刷機器メーカーを源流に持つ。",
    strengths: ["洗浄装置で世界トップシェア", "微細化に伴う洗浄工程増加が追い風", "京都発の独自技術文化"],
    rivals: ["tel", "lam-research"],
    colors: ["#22d3ee", "#155e75"],
  },
  {
    id: "disco",
    name: "ディスコ",
    nameJa: "Disco Corporation",
    country: "日本",
    flag: "🇯🇵",
    region: "japan",
    segments: ["equipment"],
    revenueUsdB: 2.1,
    operatingMarginPct: 32,
    founded: 1937,
    hq: "東京",
    tagline: "チップを1個ずつ切り出す「ダイシング」のニッチ王者。",
    businessModel:
      "ウェハーを個々のチップに切り分ける「切削・研削・研磨」装置で世界トップシェアを握るニッチ独占ビジネス。刃物（砥石）の消耗品販売も収益源。",
    strengths: ["ダイシング装置でほぼ独占的シェア", "消耗品（砥石）による継続収益", "独自の人事評価制度で知られる企業文化"],
    rivals: [],
    colors: ["#67e8f9", "#0e7490"],
  },
  {
    id: "shinetsu",
    name: "信越化学工業",
    nameJa: "Shin-Etsu Chemical",
    country: "日本",
    flag: "🇯🇵",
    region: "japan",
    segments: ["materials"],
    revenueUsdB: 15,
    operatingMarginPct: 20,
    founded: 1926,
    hq: "東京",
    tagline: "シリコンウェハーの世界シェア首位を握る総合化学メーカー。",
    businessModel:
      "塩化ビニル樹脂などの総合化学品事業に加え、半導体の基板となるシリコンウェハーで世界最大級のシェアを持つ。半導体材料は事業の一部門ながら収益の柱の一つ。",
    strengths: ["シリコンウェハーで世界シェア首位級", "化学品事業との分散による安定性", "フォトレジストなど周辺材料にも展開"],
    rivals: ["sumco"],
    colors: ["#4ade80", "#166534"],
  },
  {
    id: "sumco",
    name: "SUMCO",
    nameJa: "サムコ",
    country: "日本",
    flag: "🇯🇵",
    region: "japan",
    segments: ["materials"],
    revenueUsdB: 2.9,
    operatingMarginPct: 15,
    founded: 1999,
    hq: "東京",
    tagline: "ウェハー専業で世界シェア2位を張る材料メーカー。",
    businessModel:
      "半導体の基板となるシリコンウェハーの製造に特化した専業メーカー。信越化学と共に世界シェアの過半を握る寡占構造の一角を成す。NEC・三菱系ウェハー事業の統合から誕生。",
    strengths: ["ウェハー専業としての高い技術特化度", "信越化学と並ぶ世界シェア", "半導体市況に業績が連動する明快な構造"],
    rivals: ["shinetsu"],
    colors: ["#86efac", "#15803d"],
  },
];
